language: node_js
node_js:
  - node
  - "6"
  - "8"
  - "10"
  - "11"

jobs:
  include:
    - stage: test
      name: "Tests"
      script: "yarn test"
    - stage: lint
      name: "Linting"
      script: "yarn lint"
    - stage: build
      name: "Build"
      script: "yarn build"

stages:
  - test
  - lint
  - build

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  email: "dlaubrei@gmail.com"

