language: nodejs

before_script:
  - yarn
  - yarn run build

script:
  - yarn run test
  - yarn run lint

after_success:
  - yarn run typedoc
  - yarn pack

deploy:
  - provider: npm
    skip_cleanup: true
    email: "dlaubrei@gmail.com"
    api_key: $NPM_API_KEY
