language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: test
      name: "Tests"
      script: "yarn test"
    - stage: lint
      name: "Linting"
      script: "yarn lint"
    - stage: build
      name: "Build"
      script: "yarn build"

stages:
  - test
  - lint
  - build

deploy:
  provider: npm
  api_key: $NPM_API_KEY
  skip_cleanup: true
  email: "dlaubrei@gmail.com"

